import Head from 'next/head'
import { useRouter } from 'next/router'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import nextI18NextConfig from '../next-i18next.config'
import { useTranslation } from 'next-i18next';

import MultipleContent from '/components/multiple-content.js'
import BlogCard from "/components/blog-card.js";


export async function getStaticProps({ locale }){
  return {
    props: {
        ...(await serverSideTranslations(locale, process.env.localesFiles, nextI18NextConfig ))
    }
  }
}

export default function Blog() {
  const { t } = useTranslation(process.env.localesFiles);
  const router = useRouter();
  const blogContent = t('blogItems', { returnObjects: true, ns: router.localeFile });

  return (
    <>
      <Head>
        <title>Blog | Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='mt-5'>
    
      {/* <div className='text-3xl font-bold underline'> { t('blogHeading') } </div>   */}
        <section className="section div-lower">
          <div className="container">

            {
            
            blogContent.map((item, index) => (
              <BlogCard
                title={item.blogHeading}
                description={item.description}
                image={item.image.src}
                imageAlt={item.image.alt}
                link={item.blogId}
                key={index}
              />
              
             /*  {item.image.map((subItem, subIndex) => (
                  <div className="mt-5" key={subIndex}>
                    <Image
                      src={subItem.src}
                      alt={subItem.alt}
                      width={360}
                      height={540}
                    />
                  </div>
                ))} */

            ))}
            
            {  }

          </div>

          {/* <MultipleContent/> */}
        </section>
      </main>
    </>
  )
}
