import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import nextI18NextConfig from '../next-i18next.config'
import { useTranslation } from 'next-i18next';

import MultipleContent from '/components/multiple-content.js'


export async function getStaticProps({ locale }){
  return {
    props: {
        ...(await serverSideTranslations(locale, process.env.localesFiles, nextI18NextConfig ))
    }
  }
}

export default function Home() {

  const { t } = useTranslation(process.env.localesFiles);
  const router = useRouter();
  const homeContent = t('homeContent', { returnObjects: true, ns: router.localeFile });
  
  return (
    <>
      <Head>
        <title>Home | Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='mt-5'>
        <div className="container mx-auto px-5">
          
          <div className='text-3xl font-bold underline'> { t('homeHeading', { ns: router.localeFile }) } </div> 

          <div>
            <ul className="list-none mt-3">
              {
                  homeContent.map((item , index) => (
                    <li className={index == 0 ? '' : 'mt-5'} key={index}>
                        <b className='mb-5'>{item.title}</b>
                        <br></br>
                        {item.description}
                      { 
                        item.image.map((subItem , subIndex) => (
                          <div className='mt-5' key={subIndex}>
                            <Image
                              src={subItem.src}
                              alt={subItem.alt}
                              width={360}
                              height={540}
                              
                            />
                          </div>
                        ))
                      }
                    </li>
                  ))
              }
            </ul>
          </div>
          <div>
            <MultipleContent/>
          </div>
        </div>  
      </main>
    </>
  )
}
