import Head from 'next/head'
import Image from 'next/image'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import nextI18NextConfig from '../next-i18next.config'
import { useTranslation } from 'next-i18next';


// process.env.localesFiles

export async function getStaticProps({ locale }){
  return {
    props: {
        ...(await serverSideTranslations(locale, ["common"], nextI18NextConfig ))
    }
  }
}

export default function Home() {

  const { t, i18n } = useTranslation();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div>{ t('selectLanguage') }</div>
      </main>
    </>
  )
}
